# Generated by Django 3.0.7 on 2020-06-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.UUIDField(auto_created=True, unique=True, verbose_name='ИД')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Отчество')),
                ('lastName', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('nickName', models.CharField(max_length=50, unique=True, verbose_name='Ник нейм')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта')),
                ('phone', models.IntegerField(max_length=10, unique=True, verbose_name='Сотовый телефон')),
            ],
        ),
    ]
