# Generated by Django 3.0.7 on 2020-06-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(unique=True, verbose_name='Сотовый телефон'),
        ),
    ]
