# Generated by Django 3.0.7 on 2020-06-07 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200608_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='UUID',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='person',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('0bcd64bc-5f10-4502-a78c-7d6e760af684'), editable=False, primary_key=True, serialize=False, verbose_name='ИД'),
        ),
    ]
