# Generated by Django 3.0.7 on 2020-06-07 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20200608_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('6dfc7256-d3ad-4b4f-a68f-bc5c2e34948a'), editable=False, primary_key=True, serialize=False, verbose_name='ИД'),
        ),
    ]
