# Generated by Django 3.0.7 on 2020-06-07 20:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20200608_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='social.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('549b3365-bc4a-4772-8b83-760fa9b195c0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
