# Generated by Django 3.0.7 on 2020-06-07 20:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200608_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='account',
            name='login',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=1, max_length=255, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('0202a055-3bec-4deb-acb6-edfeb20ae1ce'), editable=False, primary_key=True, serialize=False),
        ),
    ]
